server:
  port: 8591




westf:
  security:
    broswer:
      loginPage: /signIn.html
      loginType: JSON
      defaultPage: /index.html
      rememberMeSeconds: 3600
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 520520


